### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by xeruf** [solidusio/solidus_starter_frontend#222]
Using default solidus version on ruby 3 and rails 6.1.5 I am unable to run this:
```
DEPRECATION WARNING: This manually engine loading is deprecated and will be removed in v3.0.0. Remove `require "view_component/engine"`. (called from block (2 levels) in require at /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60)
DEPRECATION WARNING: Manually loading the engine is deprecated and will be removed in v3.0.0. Remove `require "view_component/engine"`. (called from block (2 levels) in require at /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60)
/home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:587:in `add_route': Invalid route name, already in use: 'new_spree_user_session' 
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
https://guides.rubyonrails.org/routing.html#restricting-the-routes-created (ArgumentError)
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1986:in `add_route'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1957:in `decomposed_match'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1955:in `block in decomposed_match'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1554:in `block (2 levels) in member'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1886:in `path_scope'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1554:in `block in member'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1766:in `with_scope_level'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1548:in `member'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1955:in `decomposed_match'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1926:in `block in map_match'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1924:in `each'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1924:in `map_match'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1663:in `match'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:765:in `map_method'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:718:in `get'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails/routes.rb:379:in `block in devise_session'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1322:in `block (2 levels) in resource'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1774:in `block in resource_scope'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:916:in `controller'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1774:in `resource_scope'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1321:in `block in resource'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1766:in `with_scope_level'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1319:in `resource'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails/routes.rb:378:in `devise_session'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails/routes.rb:268:in `block (4 levels) in devise_for'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails/routes.rb:268:in `each'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails/routes.rb:268:in `block (3 levels) in devise_for'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails/routes.rb:472:in `with_devise_exclusive_scope'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails/routes.rb:267:in `block (2 levels) in devise_for'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails/routes.rb:370:in `block in devise_scope'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1030:in `block in constraints'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:901:in `scope'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/ma              pper.rb:1030:in `constraints'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails/routes.rb:369:in `devise_scope'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails/routes.rb:266:in `block in devise_for'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails/routes.rb:242:in `each'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails/routes.rb:242:in `devise_for'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/solidus_auth_devise-2.5.4/config/routes.rb:5:in `block in <main>'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:655:in `instance_exec'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:655:in `block in with_default_scope'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:901:in `scope'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:654:in `with_default_scope'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:425:in `eval_block'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:409:in `draw'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/solidus_auth_devise-2.5.4/config/routes.rb:3:in `<main>'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/railties-6.1.5/lib/rails/application/routes_reloader.rb:47:in `block in load_paths'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/railties-6.1.5/lib/rails/application/routes_reloader.rb:47:in `each'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/railties-6.1.5/lib/rails/application/routes_reloader.rb:47:in `load_paths'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/railties-6.1.5/lib/rails/application/routes_reloader.rb:21:in `reload!'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/railties-6.1.5/lib/rails/application/routes_reloader.rb:35:in `block in updater'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.5/lib/active_support/file_update_checker.rb:83:in `execute'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/railties-6.1.5/lib/rails/application/routes_reloader.rb:10:in `execute'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/railties-6.1.5/lib/rails/application/finisher.rb:195:in `block in <module:Finisher>'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/railties-6.1.5/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/railties-6.1.5/lib/rails/initializable.rb:32:in `run'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/railties-6.1.5/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/railties-6.1.5/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/railties-6.1.5/lib/rails/application.rb:391:in `initialize!'
	from /home/janek/data/1-projects/ftt/solidcluster/config/environment.rb:5:in `<main>'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/activesupport-6.1.5/lib/active_support/dependencies.rb:332:in `require'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:108:in `preload'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:162:in `serve'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:144:in `block in run'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:138:in `loop'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:138:in `run'
	from /home/janek/data/1-projects/ftt/solidcluster/vendor/cache/ruby/3.0.0/gems/spring-4.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'
```
This runs http://demo.solidus.io, right? That means the demo does not run on the latest versions?

**Comment by kennyadsl** [comment]
Hey @xeruf, which commands did you run exactly to get this error?

**Comment by gsmendoza** [comment]
Hi @xeruf, @kennyadsl! I was able to install SolidusStarterFrontend on a Ruby 3.0.0, Rails 6.1.5 app.

http://demo.solidus.io is currently running on the last gem version of SolidusStarterFrontend,  v0.1.0 at rev 709e44e93dbedf46cfa502e783f0bda6f301596a. The latest version of SolidusStarterFrontend in master is now a Rails application template.

CC @waiting-for-dev

**Comment by xeruf** [comment]
I followed the installation procedure and tried multiple times, will get back...

**Comment by antonioJASR** [comment]
Hi @xeruf 

 I got the same problem, after reading the README.md again I notice this `"you need to exclude solidus_frontend gem "`, so I changed my Gemfile from:

`gem 'solidus', "~> 3.1"`
 
to:

```
gem 'solidus_core', "~> 3.1"
gem 'solidus_api', "~> 3.1"
gem 'solidus_backend', "~> 3.1"
gem 'solidus_sample', "~> 3.1"
```

and it works, I hope it helps.

**Comment by kennyadsl** [comment]
@xeruf let us know if you are still experiencing issues with the installer and we can reopen this issue. Thanks again for submitting it.

**Comment by xeruf** [comment]
Didn't get it to work and stayed with the default for now

**Comment by waiting-for-dev** [comment]
> Can you specify the recommended ruby and rails version?

Hey @citin, you can use Solidus from master and the latest Ruby and Rails. If you run `bin/rails g solidus:install`, you'll be prompted to install `solidus_starter_frontend` from there. Solidus v3.2 will be released very soon.
